schema_version = "1.0.0"

id = "sourceenginecollisiontools"
version = "1.5.1"
name = "Source Engine Collision Tools"
tagline = "Generate & optimize collision models for use in Source Engine"
maintainer = "Theanine3D <theanine3d@gmail.com>"

type = "add-on"

website = "https://github.com/theanine3D/source-engine-collision-tools"

tags = ["Mesh", "Object", "Game Engine"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2024 Pedro Valencia"]

[permissions]
files = "Export collision-related QC and VMF files"
